### ISSUE TITLE
Missing check whether node name matches a device

### ISSUE THREAD

**Issue by janiskemper** [hivelocity/hivelocity-cloud-controller-manager#18]
## Description

The InstancesV2 interface (https://pkg.go.dev/k8s.io/cloud-provider#InstancesV2) expects also that we check whether the node name matches any device.

This is currently not implemented and could lead to a situation where the CCM concludes that a device is missing even though it actually exists.

We have to list devices and check whether some caphv-machine-name label matches the node name. If so, this is the desired device.

**Comment by aniruddha2000** [comment]
Approach -

- Implement another util func like `getHivelocityDeviceIDFromNode(node)` which return a `caphv-machine-name` from the node.
- Implement another function that use the name to get devices like `i2.client.GetBareMetalDevice(ctx, deviceID)` does.
