### ISSUE TITLE
Fix InstanceExists to only return true if device is part of the cluster

### ISSUE THREAD

**Issue by janiskemper** [hivelocity/hivelocity-cloud-controller-manager#19]
## Description

Currently, we return that an instance exists if we find the device in the API. However, this does not mean that the device is actually part of the cluster. For this, we need to check in the labels for the caphv-machine-name and see whether it matches the node name.

**Comment by aniruddha2000** [comment]
Question - 

https://github.com/hivelocity/hivelocity-cloud-controller-manager/blob/a5e312e2c59de418bbd842615f340147b469c6f7/pkg/hvutils/hvutils.go#L46 I see this util function dealing with labels, but it says `caphv-device-type` and you say `caphv-machine-name` is device and machine is same?


Approach - 

- Add a new utils function to return the `caphv-machine-name` and check in the InstanceExists that if name matches with the label value or not
